baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'home/'
theme = "hugo-coder"
defaultcontentlanguage = "en"

paginate = 20

[markup.highlight]
style = "github-dark"

[markup.goldmark.renderer]
unsafe = true

[params]
    author = "AGNAY BAKSHI"
    info = "**MECHATRONICS ENGINEER**"
    description = "BAKSJI JI's personal website"
    keywords = "Blog,developer,personal"
    avatarurl = "https://avatars.githubusercontent.com/u/71760372?s=400&u=86813cd3b3ad0c3994cb6b7a2d8f43eba5e3b9d4&v=4"


    since = 2023

    enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

  [taxonomies]
    category = "categories"
    series = "series"
    tag = "EDA,Analysis,GameJam,GameDev,Unity,Python,C#"
    author = "authors"

     #Social links
    [[params.social]]
    name = "Email"
    icon = "fa fa-envelope fa-2x"
    weight = 2
    url = "mailto:agnaybakshi@gmail.com"
    [[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/agnaybakshi"
    [[params.social]]
    name = "Linkedin"
    icon = "fa fa-linkedin fa-2x"
    weight = 1
    url = "https://www.linkedin.com/in/akhil-sharma-👓-35a880202/"
    [[params.social]]
    name = "Medium"
    icon = "fa fa-medium fa-2x"
    weight = 1
    url = "https://medium.com/@Akhilsharma30"

    #Main Links
    [[menu.main]]
    name = "About"
    weight = 1
    url = "about/"
    [[menu.main]]
    name = "Blog"
    weight = 2
    url = "post/"
    [[menu.main]]
    name = "Open-Source"
    weight = 2
    url = "opensource/"
    [[menu.main]]
    name = "Supervised"
    weight = 2
    url = "supervised/"
    [[menu.main]]
    name = "CV"
    weight = 3
    url = "cv/"
    [[menu.main]]
    name = "ChatBot"
    weight = 4
    url = "chatbot/"

    

